# Generated by Django 4.2.4 on 2023-09-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bookstore_bookname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookstore',
            old_name='Description',
            new_name='description',
        ),
    ]
